CREATE TABLE IF NOT EXISTS mpa_rating
(
    mpa_rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating VARCHAR UNIQUE
);

CREATE TABLE IF NOT EXISTS film
(
    film_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_title               VARCHAR NOT NULL,
    film_description         VARCHAR(200),
    release_date        DATE,
    film_duration INTEGER CHECK (film_duration > 0),
    mpa_rating_id       INTEGER REFERENCES mpa_rating (mpa_rating_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  BIGINT  NOT NULL REFERENCES film (film_id),
    genre_id INTEGER NOT NULL REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR NOT NULL,
    login    VARCHAR NOT NULL,
    name     VARCHAR NOT NULL,
    birthday DATE    NOT NULL
);

CREATE TABLE IF NOT EXISTS user_friendship
(
    from_user_id BIGINT  NOT NULL REFERENCES users (user_id),
    to_user_id   BIGINT  NOT NULL REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS film_like
(
    film_id BIGINT NOT NULL REFERENCES film (film_id),
    user_id BIGINT NOT NULL REFERENCES users (user_id)
);
